modLoader="javafml"
loaderVersion="[39,)"
license="MIT License"
issueTrackerURL="https://github.com/Itskillerluc/Alchemical_Brewery/issues"
[[mods]]
modId="alchemicalbrewery"
version="${file.jarVersion}"
displayName="Alchemical Brewery"
# displayURL="https://itskillerluc.github.io/Alechemical_Brewery"
logoFile="icon.png"
credits="Almost everything was done by Itskillerluc."
authors="Itskillerluc"
description='''
This mod adds various magic machines to craft with the elements o
f fire, earth, water 
            and air. It allow
            s you to create several items that do things.
'''
[[dependencies.alchemicalbrewery]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.alchemicalbrewery]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
